server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userService
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: jobService
          uri: lb://job-service
          predicates:
            - Path=/api/v1/jobs/**
        - id: applicationService
          uri: lb://application-service
          predicates:
            - Path=/api/v1/applications/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT