spring:
  application:
    name: application-service
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://postgres:5432/applications_db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  main:
    banner-mode: off
  kafka:
    consumer:
      bootstrap-servers: broker:9092

server:
  port: 8081

